/* Verify the three security features:
   1. forced password change for accounts whose password someone else set
   2. session listing and revocation
   3. sign-in throttling and lockout. */

"use strict";

const fs = require("fs");
const path = require("path");
const http = require("http");
const { spawn } = require("child_process");

const DIR = "C:\\Users\\user\\Downloads\\Letter";
const PORT = 8861;
const BASE = "http://127.0.0.1:" + PORT;

let pass = 0, fail = 0;
function check(n, c, d) { if (c) { pass++; console.log("  PASS  " + n); } else { fail++; console.log("  FAIL  " + n + (d ? "  -> " + d : "")); } }

const DATA = path.join(DIR, "data");
if (fs.existsSync(DATA)) fs.rmSync(DATA, { recursive: true, force: true });

/* Deliberately no ADMIN_PASS: this suite tests the path where the password
   is generated by the server and therefore must be changed at first
   sign-in. That is the real fresh-install experience. */
const server = spawn(process.execPath, ["server.js"], {
  cwd: DIR,
  env: Object.assign({}, process.env, { PORT: String(PORT), ADMIN_USER: "root", ADMIN_PASS: "" }),
  stdio: ["ignore", "pipe", "pipe"]
});
let serverOut = "";
server.stdout.on("data", d => serverOut += d.toString());
server.stderr.on("data", d => serverOut += d.toString());

/* Read the generated password out of the console banner, the way an
   operator would. */
let seedPassword = null;
function captureSeedPassword() {
  const m = serverOut.match(/password:\s*(\S+)/);
  if (m) seedPassword = m[1];
  return seedPassword;
}

function req(method, urlPath, body, cookie, headers) {
  return new Promise(function (resolve, reject) {
    const data = body === undefined || body === null ? null : JSON.stringify(body);
    const h = Object.assign({ "Content-Type": "application/json" },
      cookie ? { Cookie: cookie } : {}, headers || {});
    if (data) h["Content-Length"] = Buffer.byteLength(data);
    const r = http.request(BASE + urlPath, { method: method, headers: h }, function (res) {
      const chunks = [];
      res.on("data", c => chunks.push(c));
      res.on("end", function () {
        const raw = Buffer.concat(chunks);
        let json = null;
        try { json = JSON.parse(raw.toString("utf8")); } catch (e) {}
        resolve({ status: res.statusCode, json: json, text: raw.toString("utf8"),
          headers: res.headers,
          cookie: res.headers["set-cookie"] ? res.headers["set-cookie"][0].split(";")[0] : null });
      });
    });
    r.on("error", reject);
    if (data) r.write(data);
    r.end();
  });
}

function waitForServer() {
  return new Promise(function (resolve, reject) {
    let n = 0;
    (function go() {
      n++;
      const r = http.request(BASE + "/api/me", function (res) { res.resume(); resolve(); });
      r.on("error", function () { n > 100 ? reject(new Error("no start:\n" + serverOut)) : setTimeout(go, 150); });
      r.end();
    })();
  });
}

(async function run() {
  try {
    await waitForServer();

    console.log("=== 1. the seed admin must change its password ===");
    let admin = null;
    {
      seedPassword = captureSeedPassword();
      check("the generated password is printed once", Boolean(seedPassword), String(seedPassword));
      const login = await req("POST", "/api/login", { username: "root", password: seedPassword });
      check("the seed admin can sign in", login.status === 200, String(login.status));
      check("sign-in says a change is required", login.json.mustChangePassword === true,
        JSON.stringify(login.json.mustChangePassword));
      admin = login.cookie;

      const me = await req("GET", "/api/me", undefined, admin);
      check("and /api/me reports it too", me.json.mustChangePassword === true,
        JSON.stringify(me.json.mustChangePassword));

      // ordinary routes are refused until the change happens
      const files = await req("GET", "/api/files", undefined, admin);
      check("listing files is refused", files.status === 403, String(files.status));
      check("with an explanation", /new password/i.test(files.json.error || ""),
        JSON.stringify(files.json));
      check("and a flag the UI can act on", files.json.mustChangePassword === true);

      const mail = await req("GET", "/api/mail?folder=inbox", undefined, admin);
      check("mail is refused too", mail.status === 403, String(mail.status));

      // but the routes needed to fix it work
      const stillMe = await req("GET", "/api/me", undefined, admin);
      check("/api/me still works", stillMe.status === 200, String(stillMe.status));

      /* The public avatar route is reachable while a change is pending,
         because avatars appear on shared letters where there is no session. */
      const av = await req("GET", "/avatar/nobody");
      check("the public avatar route is reachable", av.status === 404, String(av.status));

      // the actual change
      const badCurrent = await req("POST", "/api/password",
        { current: "wrongpassword", next: "brandnewpass1" }, admin);
      check("a wrong current password is refused", badCurrent.status === 401, String(badCurrent.status));

      const tooShort = await req("POST", "/api/password",
        { current: seedPassword, next: "short" }, admin);
      check("a too-short new password is refused", tooShort.status === 400, JSON.stringify(tooShort.json));

      const same = await req("POST", "/api/password",
        { current: seedPassword, next: seedPassword }, admin);
      check("reusing the same password is refused", same.status === 400, JSON.stringify(same.json));

      const changed = await req("POST", "/api/password",
        { current: seedPassword, next: "brandnewpass1" }, admin);
      check("the change succeeds", changed.status === 200, JSON.stringify(changed.json));

      // and now everything opens up
      const after = await req("GET", "/api/files", undefined, admin);
      check("files are reachable afterwards", after.status === 200, String(after.status));

      const meAfter = await req("GET", "/api/me", undefined, admin);
      check("the pending flag is cleared", meAfter.json.mustChangePassword === false,
        JSON.stringify(meAfter.json.mustChangePassword));

      // the old password no longer works, the new one does
      const oldLogin = await req("POST", "/api/login", { username: "root", password: seedPassword });
      check("the old password stops working", oldLogin.status === 401, String(oldLogin.status));
      const newLogin = await req("POST", "/api/login", { username: "root", password: "brandnewpass1" });
      check("the new password works", newLogin.status === 200, String(newLogin.status));
      check("and no change is required now", newLogin.json.mustChangePassword === false,
        JSON.stringify(newLogin.json.mustChangePassword));
      admin = newLogin.cookie;
    }

    console.log("\n=== an admin-set password forces a change ===");
    {
      const created = await req("POST", "/api/admin/users",
        { username: "alice", password: "alicepassword", role: "user" }, admin);
      const aliceLogin = await req("POST", "/api/login", { username: "alice", password: "alicepassword" });
      check("a self-created account can sign in", aliceLogin.status === 200, String(aliceLogin.status));
      check("and is not forced to change",
        aliceLogin.json.mustChangePassword === false, JSON.stringify(aliceLogin.json.mustChangePassword));

      // the admin resets it
      const users = await req("GET", "/api/admin/users", undefined, admin);
      const aliceId = users.json.users.filter(u => u.username === "alice")[0].id;
      const reset = await req("POST", "/api/admin/password",
        { id: aliceId, password: "setbyadmin1" }, admin);
      check("the admin can set a password", reset.status === 200, JSON.stringify(reset.json));

      const afterReset = await req("POST", "/api/login", { username: "alice", password: "setbyadmin1" });
      check("the imposed password forces a change", afterReset.json.mustChangePassword === true,
        JSON.stringify(afterReset.json.mustChangePassword));
      const blocked = await req("GET", "/api/files", undefined, afterReset.cookie);
      check("and the account is restricted", blocked.status === 403, String(blocked.status));
    }

    console.log("\n=== 2. session listing and revocation ===");
    {
      const a = await req("POST", "/api/login",
        { username: "root", password: "brandnewpass1" }, null,
        { "User-Agent": "TestBrowser/A" });
      const b = await req("POST", "/api/login",
        { username: "root", password: "brandnewpass1" }, null,
        { "User-Agent": "TestBrowser/B" });
      const c = await req("POST", "/api/login",
        { username: "root", password: "brandnewpass1" }, null,
        { "User-Agent": "TestBrowser/C" });

      const list = await req("GET", "/api/sessions", undefined, a.cookie);
      check("sessions can be listed", list.status === 200 && Array.isArray(list.json.sessions),
        String(list.status));
      check("there are at least three", list.json.sessions.length >= 3,
        String(list.json.sessions.length));
      check("exactly one is marked current",
        list.json.sessions.filter(s => s.current).length === 1,
        String(list.json.sessions.filter(s => s.current).length));
      check("the device is recorded",
        list.json.sessions.some(s => /TestBrowser\/A/.test(s.agent || "")),
        JSON.stringify(list.json.sessions.map(s => s.agent)));
      check("no raw token is exposed",
        !list.json.sessions.some(s => s.id && s.id.length > 32),
        "a token-like id was returned");

      // revoke B from A
      const targetB = list.json.sessions.filter(s => /TestBrowser\/B/.test(s.agent))[0];
      const rev = await req("DELETE", "/api/sessions?id=" + targetB.id, undefined, a.cookie);
      check("another session can be revoked", rev.status === 200, JSON.stringify(rev.json));
      check("it was not the current one", rev.json.wasCurrent === false);

      const bStillWorks = await req("GET", "/api/me", undefined, b.cookie);
      check("the revoked session stops working", bStillWorks.json.user === null,
        JSON.stringify(bStillWorks.json.user));
      const aStillWorks = await req("GET", "/api/me", undefined, a.cookie);
      check("the current one is unaffected", aStillWorks.json.user !== null);

      // a bogus id is refused
      const bogus = await req("DELETE", "/api/sessions?id=deadbeefdeadbeef", undefined, a.cookie);
      check("an unknown session id is refused", bogus.status === 404, String(bogus.status));

      /* You cannot revoke someone else's. Alice is still under a forced
         password change, so she has to clear that before she has sessions
         worth testing against. */
      const aliceLogin = await req("POST", "/api/login", { username: "alice", password: "setbyadmin1" });
      await req("POST", "/api/password",
        { current: "setbyadmin1", next: "aliceownpass1" }, aliceLogin.cookie);
      const aliceAgain = await req("POST", "/api/login",
        { username: "alice", password: "aliceownpass1" });
      const aliceSessions = await req("GET", "/api/sessions", undefined, aliceAgain.cookie);
      check("alice has a session to target", aliceSessions.json.sessions.length >= 1,
        String(aliceSessions.json.sessions.length));
      const aliceSessionId = aliceSessions.json.sessions[0].id;
      const cross = await req("DELETE", "/api/sessions?id=" + aliceSessionId, undefined, a.cookie);
      check("you cannot revoke another account's session", cross.status === 404, String(cross.status));

      // revoking all others keeps you signed in
      const all = await req("DELETE", "/api/sessions?all=1", undefined, a.cookie);
      check("sign out everywhere works", all.status === 200 && all.json.removed >= 1,
        JSON.stringify(all.json));
      const cStillWorks = await req("GET", "/api/me", undefined, c.cookie);
      check("the other session is gone", cStillWorks.json.user === null);
      const aStill = await req("GET", "/api/me", undefined, a.cookie);
      check("and the caller stays signed in", aStill.json.user !== null);

      // revoking your own current session signs you out
      const mine = await req("GET", "/api/sessions", undefined, a.cookie);
      const current = mine.json.sessions.filter(s => s.current)[0];
      const selfRev = await req("DELETE", "/api/sessions?id=" + current.id, undefined, a.cookie);
      check("revoking the current session reports it", selfRev.json.wasCurrent === true);
      const afterSelf = await req("GET", "/api/me", undefined, a.cookie);
      check("and signs you out", afterSelf.json.user === null);
    }

    console.log("\n=== a password change ends other sessions ===");
    {
      const a = await req("POST", "/api/login", { username: "root", password: "brandnewpass1" });
      const b = await req("POST", "/api/login", { username: "root", password: "brandnewpass1" });

      const changed = await req("POST", "/api/password",
        { current: "brandnewpass1", next: "anotherpass12" }, a.cookie);
      check("the change succeeds", changed.status === 200, JSON.stringify(changed.json));
      check("it reports the other sessions ended", changed.json.otherSessionsEnded >= 1,
        JSON.stringify(changed.json.otherSessionsEnded));

      const bAfter = await req("GET", "/api/me", undefined, b.cookie);
      check("the other session is dead", bAfter.json.user === null);
      const aAfter = await req("GET", "/api/me", undefined, a.cookie);
      check("the caller stays signed in", aAfter.json.user !== null);
    }

    console.log("\n=== 3. sign-in throttling ===");
    {
      // a fresh account so the throttling does not disturb the others
      await req("POST", "/api/admin/users",
        { username: "target", password: "targetpass12", role: "user" }, admin);

      const results = [];
      for (let i = 0; i < 8; i++) {
        const r = await req("POST", "/api/login",
          { username: "target", password: "definitely-wrong" }, null,
          { "User-Agent": "ThrottleTest" });
        results.push(r.status);
      }
      console.log("  attempt statuses: " + JSON.stringify(results));

      check("early wrong attempts are plain 401s",
        results.slice(0, 3).every(s => s === 401), JSON.stringify(results.slice(0, 3)));
      check("attempts eventually get 429", results.some(s => s === 429), JSON.stringify(results));

      const locked = await req("POST", "/api/login",
        { username: "target", password: "targetpass12" }, null,
        { "User-Agent": "ThrottleTest" });
      check("the lockout blocks even the right password", locked.status === 429, String(locked.status));
      check("it says how long", /minute|second/i.test(locked.json.error || ""), locked.json.error);
      check("and sets Retry-After", Boolean(locked.headers["retry-after"]),
        String(locked.headers["retry-after"]));

      /* The lockout is keyed on account + client address. A spoofed
         X-Forwarded-For must NOT get round it, because the header is only
         trusted behind a proxy we control. */
      const spoofed = await req("POST", "/api/login",
        { username: "target", password: "targetpass12" }, null,
        { "User-Agent": "ThrottleTest", "X-Forwarded-For": "203.0.113.9" });
      check("a spoofed X-Forwarded-For does not dodge the lockout", spoofed.status === 429,
        String(spoofed.status));

      // an unrelated account is untouched
      const otherUser = await req("POST", "/api/login",
        { username: "root", password: "anotherpass12" }, null,
        { "User-Agent": "ThrottleTest" });
      check("another account is unaffected", otherUser.status === 200, String(otherUser.status));
    }

    console.log("\n=== throttling resets on a good sign-in ===");
    {
      /* The earlier "sign out everywhere" ended the admin session this
         block was reusing, so sign in again first. */
      const admin2 = await req("POST", "/api/login",
        { username: "root", password: "anotherpass12" });
      check("the admin can sign back in", admin2.status === 200, String(admin2.status));

      const made = await req("POST", "/api/admin/users",
        { username: "resetter", password: "resetterpass1", role: "user" }, admin2.cookie);
      check("a fresh account is created for the reset test", made.status === 200,
        JSON.stringify(made.json));

      // three failures: still within the free attempts
      for (let i = 0; i < 3; i++) {
        await req("POST", "/api/login", { username: "resetter", password: "nope" }, null,
          { "User-Agent": "ResetTest" });
      }
      const good = await req("POST", "/api/login",
        { username: "resetter", password: "resetterpass1" }, null, { "User-Agent": "ResetTest" });
      check("the right password still works within the free attempts", good.status === 200,
        String(good.status));

      // and the counter is cleared, so the next failure is free again
      const afterFail = await req("POST", "/api/login",
        { username: "resetter", password: "nope" }, null, { "User-Agent": "ResetTest" });
      check("failures were cleared by the success", afterFail.status === 401, String(afterFail.status));
      const goodAgain = await req("POST", "/api/login",
        { username: "resetter", password: "resetterpass1" }, null, { "User-Agent": "ResetTest" });
      check("and the account still signs in", goodAgain.status === 200, String(goodAgain.status));
    }

  } catch (err) {
    if (/ECONNRESET|ECONNREFUSED/.test(err.message) && fail === 0) {
      console.log("\n  (server closed while the last response was in flight -- ignoring)");
    } else {
      console.log("\n  TEST ERROR: " + err.message);
      console.log(err.stack.split("\n").slice(0, 4).join("\n"));
      fail++;
    }
  } finally {
    try { server.kill(); } catch (e) {}
    setTimeout(function () {
      if (fs.existsSync(DATA)) fs.rmSync(DATA, { recursive: true, force: true });
      console.log("\n----------------------------------------");
      console.log("PASS " + pass + "   FAIL " + fail);
      process.exit(fail ? 1 : 0);
    }, 400);
  }
})();
